tabWidth: 4
singleQuote: true
semi: false
vueIndentScriptAndStyle: true
trailingComma: all
jsxSingleQuote: false
printWidth: 160
overrides:
  - files: ['*.vue']
    options:
      printWidth: 120
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2
