/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  twitch: {
    enable: boolean;
    chatBot: boolean;
  };
  discord: {
    test: boolean;
    token: string;
    serverID: string;
    commandChannelID: string;
    voiceChannelID: string;
    ignoredUsers?: string[];
  };
  donationtracker: {
    enable: boolean;
    url: string;
    eventSlug: string;
  };
  obs: {
    address: string;
    password: string;
    discordAudio: string;
    nodecgAudio: string;
  };
  esaRepeaterPostKey: string;
  [k: string]: any;
}
