export type Games = {
    instrument1: boolean | undefined
    instrument2: boolean | undefined
    instrument3: boolean | undefined
    instrument4: boolean | undefined
    instrument5: boolean | undefined
    instrument6: boolean | undefined
    instrument7: boolean | undefined
    instrument8: boolean | undefined
    sword: number | undefined
    feather: boolean | undefined
    bracelet: number | undefined
    boots: boolean | undefined
    flippers: boolean | undefined
    hookshot: boolean | undefined
    shield: number | undefined
    rod: boolean | undefined
    shovel: boolean | undefined
    bow: boolean | undefined
    bombs: boolean | undefined
    leafs: number | undefined
    boomerang: boolean | undefined
    powder: boolean | undefined
    ocarina: boolean | undefined
    ballad: boolean | undefined
    mambo: boolean | undefined
    song: boolean | undefined
    tailkey: boolean | undefined
    anglerkey: boolean | undefined
    facekey: boolean | undefined
    birdkey: boolean | undefined
    slimekey: boolean | undefined
    rooster: boolean | undefined
}
