export type Games = {
    ep_boss?: boolean
    ep_reward?: number
    dp_boss?: boolean
    dp_reward?: number
    th_boss?: boolean
    th_reward?: number
    pod_boss?: boolean
    pod_reward?: number
    sp_boss?: boolean
    sp_reward?: number
    sw_boss?: boolean
    sw_reward?: number
    tt_boss?: boolean
    tt_reward?: number
    ip_boss?: boolean
    ip_reward?: number
    mm_boss?: boolean
    mm_reward?: number
    tr_boss?: boolean
    tr_reward?: number
    bow?: number
    boomerang?: number
    hookshot?: boolean
    bombs?: boolean
    powder?: boolean
    shovel?: boolean
    flute?: boolean
    mushroom?: boolean
    firerod?: boolean
    icerod?: boolean
    bombos?: boolean
    quake?: boolean
    ether?: boolean
    mushroom?: boolean
    lamp?: boolean
    hammer?: boolean
    net?: boolean
    book?: boolean
    pearl?: boolean
    bottle?: number
    somaria?: boolean
    byrna?: boolean
    cape?: boolean
    mirror?: boolean
    go?: boolean
    aga?: boolean
    glove?: boolean
    boots?: boolean
    flippers?: boolean
    halfmagic?: boolean
    sword?: number
    shield?: number
    tunic?: number
}
