/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BingoboardMode {
  boardMode: "normal" | "lockout" | "invasion" | "rowcontrol" | "draft" | "draftlockout";
  alwaysShowMarkers: boolean;
  markerRedirects: [
    "pink" | "red" | "orange" | "brown" | "yellow" | "green" | "teal" | "blue" | "navy" | "purple",
    "pink" | "red" | "orange" | "brown" | "yellow" | "green" | "teal" | "blue" | "navy" | "purple"
  ][];
}
