/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BingoboardMeta {
  boardHidden: boolean;
  playerColors: ("pink" | "red" | "orange" | "brown" | "yellow" | "green" | "teal" | "blue" | "navy" | "purple")[];
  colorCounts: {
    [k: string]: any;
  };
  colorShown: boolean;
  countShown?: boolean;
}
