/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HostingBingoboard {
  colorCounts: {
    [k: string]: number;
  };
  cells: {
    name: string;
    slot: string;
    colors: ("pink" | "red" | "orange" | "brown" | "yellow" | "green" | "teal" | "blue" | "navy" | "purple")[];
    rawColors: string;
    markers: [string | null, string | null, string | null, string | null];
  }[];
}
